{config, ...}:

{
  age = {
    # This is the path where we stored the key
    # generated by Terraform
    identityPaths = [ "/var/lib/id_ed25519" ];
    secrets = {
      pg_mp = {
        file = ../secrets/pg_mp.age;
        owner = "postgres";
        group = "postgres";
        mode = "0440";
      };
    };
  };
}
