ALTER USER lyceum WITH ENCRYPTED PASSWORD '@PG_LYCEUM_USER@';

ALTER USER application WITH ENCRYPTED PASSWORD '@PG_LYCEUM_APPLICATION_USER@';
ALTER ROLE lyceum_auth WITH ENCRYPTED PASSWORD '@PG_LYCEUM_AUTH_USER@'; 
ALTER ROLE migrations WITH ENCRYPTED PASSWORD '@PG_MIGRATION_USER@'; 
ALTER ROLE mnesia WITH ENCRYPTED PASSWORD '@PG_LYCEUM_MNESIA_USER@'; 

-- Grant permissions to users
GRANT CONNECT ON DATABASE lyceum TO migrations;
GRANT CREATE ON DATABASE lyceum TO migrations;

-- Grant default privileges for future schemas created by migrations user
ALTER DEFAULT PRIVILEGES FOR ROLE migrations GRANT ALL ON TABLES TO migrations;
ALTER DEFAULT PRIVILEGES FOR ROLE migrations GRANT ALL ON SEQUENCES TO migrations;

GRANT CONNECT ON DATABASE lyceum TO application;
GRANT CONNECT ON DATABASE lyceum TO lyceum_auth;
GRANT CONNECT ON DATABASE lyceum TO mnesia;
